# -*- coding: utf-8 -*-
"""NETFLIXX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QaKCOwwX6T-Mh-Xw6WlcAyzImdjdqRGL
"""

!pip install nltk

import re
import ast
import pickle

import numpy as np
import pandas as pd
import seaborn as sns

import nltk
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import warnings

warnings .filterwarnings('ignore' )

movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

movies.head(3)

credits.head()

movies.shape, credits.shape

movies.columns

credits.columns

movies = movies.merge(credits, on ='title')
movies.head(3)

movies[['movie_id','title','overview','genres','keywords','cast','crew']][:2]

df = movies[['movie_id','title','overview','genres','keywords','cast','crew']]
df.head(3)

df.shape

df.isnull().sum()

df['overview'].fillna(' ', inplace=True)

df.isnull().sum()

df.head(2)

df['genres']

df['genres'][0]

type(df['genres'][0])

ast.literal_eval(df['genres'][0])

for i in ast.literal_eval(df['genres'][0]):
    print(i['name'])

def fetch_genres(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

fetch_genres(df['genres'][0])

df['genres'].apply(fetch_genres)

df[:2]

df['genres'] = df['genres'].apply(fetch_genres)

df[:3]

df['keywords']

df['keywords'][0]

def fetch_keywords(text):
    l = []
    for i in ast.literal_eval(text):
        l.append(i['name'])
    return l

fetch_keywords(df['keywords'][0])

df['keywords'].apply(fetch_keywords)

df['keywords']

df.head(3)

df['cast']

df['cast'][0]

def fetch_cast(text):
    l = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter != 3:
            l.append(i['name'])
            counter += 1
        else:
            break
    return l

fetch_cast(df['cast'][0])

df['cast'] = df['cast'].apply(fetch_cast)

df[:3]

df['crew']

df['crew'][0]

def fetch_director(text):
    l = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            l.append(i['name'])

    return l

fetch_director(df['crew'][0])

df['crew'] = df['crew'].apply(fetch_director)

df.head()

df['overview']

df['overview'][0]

df['overview'][0].split()

df['overview'].apply(lambda x:x.split())

df['overview'] = df['overview'].apply(lambda x:x.split())

df.head()

def to_string_list(x):
    """Helper function to ensure elements are strings within a list."""
    if isinstance(x, str):
        return [x]
    elif isinstance(x, list):
        return [str(item) for item in x]
    else:
        return []

for col in ['overview', 'genres', 'keywords', 'cast', 'crew']:
    df[col] = df[col].apply(to_string_list)
df['combined_features'] = df['overview'] + df['genres'] + df['keywords'] + df['cast'] + df['crew']

print((df['overview'] + df['genres'] +df['keywords'] +df['cast'] + df['crew'] )[0] )

df['tags'] = df['overview'] + df['genres'] + df['keywords'] + df['cast'] + df['crew']

df.head()

df = df[['movie_id','title','tags']]
df

print(df['tags'][0])

df['tags'].apply(lambda x: [i.replace(' ',' ')for i in x])

df['tags']= df['tags'].apply(lambda x:[i.replace(' ',' ')for i in x])

print(df['tags'][0])

df.head()

df['tags'].apply(lambda x:' '.join(x))

df['tags'] = df['tags'].apply(lambda x:' '.join(x))
df

df.head()

ps = PorterStemmer()
for i in['love', 'lover', 'lovers', 'loving', 'lovely']:
  print(f'{i} ---> {ps.stem(i)}')

PorterStemmer()
def text_preprocess(text):
 new_text = []

 for i in text.split():
      lower = i.lower()
      new_text.append(ps.stem(lower))

 return" ".join(new_text)

text_preprocess(df['tags'][0])

df['tags'][0]

df['tags'].apply(text_preprocess)

df['tags'] = df['tags'].apply(text_preprocess)

df

df['tags'][1205]

cv = CountVectorizer(max_features=5000, stop_words='english')
cv

cv.fit_transform(df['tags'])

vectors = cv.fit_transform(df['tags']).toarray()
vectors

vectors.shape

cosine_similarity(vectors)

similarity = cosine_similarity(vectors)
similarity

df[:5]

distance = similarity[0]
distance

sorted(similarity[0], reverse=True)

list(enumerate(similarity[0]))

sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])[1:6]

df.iloc[0]

df.iloc[1216]

df.iloc[2409]

def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]
def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]
    distance = similarity[movie_index]

    for i in movie_list:
           print(df.iloc[i[0]].title)

def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])
    for i in movie_list[1:6]:
        print(df.iloc[i[0]].title)

recommend('Iron Man')

recommend('Captain America: Civil War')

recommend('Superman')

similarity[0]

df[df['title']== 'Avatar']

df[df['title']== 'Avatar'].index[0]

df.iloc[1216]

df.iloc[1216].title

import pickle

df

df.to_dict()

similarity

pickle.dump(df.to_dict(),open('movie_dict.pkl', mode='wb'))

pickle.dump(similarity, open('similarity.pkl', mode='wb'))

df['title'].values

list(df['title'].values)

"""Output of Movie recommendation system:-"""

movie_name = input("Enter a movie name: ")
recommend(movie_name)

"""Another Way :-"""

import ipywidgets as widgets
from IPython.display import display

movie_dropdown = widgets.Dropdown(
    options=movies['title'].tolist(),
    description='Movie:'
)

display(movie_dropdown)

button = widgets.Button(description="Recommend")

def on_button_click(b):
    recommend(movie_dropdown.value)

button.on_click(on_button_click)

display(button)